name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/
      - run: nix-build test.nix
      - run: nix-shell
